package com.mlefevre.maths.domain.enumeration;

public enum FormulaElementType {

    UNKNOWN, ARITHMETICAL_SUM, ARITHMETICAL_PRODUCT, POWER, DIFFERENT, GREATER, GREATER_OR_EQUALS, EQUALS, LOWER, LOWER_OR_EQUALS, SUM, PRODUCT, FRACTION, ROOT, LIMIT, INTEGRAL, DOUBLE_INTEGRAL, TRIPLE_INTEGRAL, UNION, INTERSECTION

}
